### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'app_name' and 'app_module'

### ISSUE THREAD

**Issue by astarrh** [edcrewe/django-csvimport#59]
Using python 3.5:

`'csvimport.app.AppConfig' applied in INSTALLED_APPS`

```
Django version 1.8.4, using settings 'AlmondKing.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/adamstarrh/almondking/AlmondKing/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/adamstarrh/almondking/AlmondKing/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/Users/adamstarrh/almondking/AlmondKing/lib/python3.5/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
TypeError: __init__() missing 2 required positional arguments: 'app_name' and 'app_module'
[03/Oct/2015 23:55:45] "GET /admin HTTP/1.1" 500 59```

**Comment by astarrh** [comment]
Oops. Time for me to go to bed i think

**Comment by vhdmsm** [comment]
@astarrh Didn't you think enough? :D i have the same problem.
Using Python3.5, Django 1.9:
```
Traceback (most recent call last):
  File "/Users/vahid/.virtualenvs/qbot/lib/python3.5/site-packages/django/apps/config.py", line 136, in create
    app_name = cls.name
AttributeError: type object 'AppConfig' has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/vahid/.virtualenvs/qbot/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/vahid/.virtualenvs/qbot/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Users/vahid/.virtualenvs/qbot/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/vahid/.virtualenvs/qbot/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/vahid/.virtualenvs/qbot/lib/python3.5/site-packages/django/apps/config.py", line 139, in create
    "'%s' must supply a name attribute." % entry)
django.core.exceptions.ImproperlyConfigured: 'csvimport.app.AppConfig' must supply a name attribute.
```

**Comment by AyeshaIshrath** [comment]
Okay, how did you guys fix this?

**Comment by astarrh** [comment]
Judging by my comment, it looks like it was a semantic error for me.
